services:
  web:
    build: .
    environment:
      - SECRET_KEY=76018c0e1a3b4c40f261d6a7fbf81a3436226bfc088ee8202b01d9eb25c12c92
      - MONGODB_URL=mongodb://admin:admin@mongo:27017
    depends_on:
      mongo:
        condition: service_started
        restart: true
    ports:
      - "8000:8000"
  mongo:
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    image: mongo
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
